# Generated by Django 3.0.3 on 2020-03-02 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_Date',
            new_name='contact_date',
        ),
    ]
