# Generated by Django 3.0.3 on 2020-03-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20200302_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='doc_file',
            field=models.FileField(null=True, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
