# Generated by Django 3.0.3 on 2020-03-14 19:30

import contacts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_doc_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='doc_file',
            field=models.FileField(null=True, upload_to='documents/%Y/%m/%d/', validators=[contacts.validators.validate_file_size]),
        ),
    ]
