# Generated by Django 3.0.3 on 2020-02-25 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Experts',
            new_name='Expert',
        ),
    ]
