# Generated by Django 3.0.3 on 2020-02-25 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_auto_20200225_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='position',
        ),
    ]
