# Generated by Django 3.0.3 on 2020-02-25 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_remove_listing_position'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acacdemic',
            new_name='Academic',
        ),
    ]
