# Generated by Django 3.0.3 on 2020-02-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_auto_20200225_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='looking_for',
            field=models.TextField(blank=True),
        ),
    ]
