# Generated by Django 3.0.3 on 2020-02-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_listing_looking_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic',
            name='position',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='benefit',
            name='position',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='dutie',
            name='position',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='skill',
            name='position',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
