# Generated by Django 3.0.3 on 2020-02-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_auto_20200225_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='position',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
